export const SET_SHORTDESCRIPTION = 'SET_SHORTDESCRIPTION'
export const SET_PROGRAMMINGLANGUAGES = 'SET_PROGRAMMINGLANGUAGES'
export const SET_FRONTENDTECHNOLOGIES = 'SET_FRONTENDTECHNOLOGIES'
export const SET_BACKENDTECHNOLOGIES = 'SET_BACKENDTECHNOLOGIES'
export const SET_DATABASES = 'SET_DATABASES'
export const SET_OTHERTOOLS = 'SET_OTHERTOOLS'

export const SET_CONTACT = 'SET_CONTACT'